- Append 'which' and 'ansible' packages to install-cli-deps.sh script. - Move configuration to ansible.cfg file. - Express variables.yml file in yaml format. - Append troubleshooting for ansible scripts to tips and tricks. - Cosmetic changes to be consistent. - Fix issue when provisioning the host. The order matter when installing vagrant plugins. - Append reference to the credentials. - Append missed dependency for openldap-clients package - Append ldapvi tool as a dependency to make it available. - Append rdesktop package dependency. - Move some dependencies to ansible scripts. - Fix 'Install additional schemas' step - Append how to execute a role from the command line with ansible - Append reference to the documentation for ldifde tool - Document the scenario for the first rdesktop, and update the command for the active directory scenario - Changes to enroll the client to the active directory more fluent. It needs review and still some changes as the template has the list of domains hardcoded; that is not wished

diff --git a/provision/roles/enroll-client/tasks/ad.yml b/provision/roles/enroll-client/tasks/ad.yml
--- a/provision/roles/enroll-client/tasks/ad.yml
+++ b/provision/roles/enroll-client/tasks/ad.yml
@@ -8,15 +8,17 @@
 - name: Join to Active Directory domain
   become: True
   shell: |
-    echo vagrant | realm join {{ ad.domain | quote }} || exit $?
+    echo vagrant | realm join -v {{ ad.domain | upper | quote }} || exit $?
+    echo vagrant | kinit {{ ad.kerberos.username }} || exit $?
     touch /etc/sssd/ad_enrolled || exit $?
   register: client_ad_installation
-  args:
-    creates: /etc/sssd/ad_enrolled
+  # args:
+  #   creates: /etc/sssd/ad_enrolled
 
 - name: Copy AD keytab to local folder
   become: True
   copy:
+    force: True
     src: /etc/krb5.keytab
     dest: '/etc/sssd/ad.keytab'
     remote_src: yes
@@ -29,5 +31,14 @@
     src: '/etc/sssd/ad.keytab'
     dest: '/shared/enrollment/{{ inventory_hostname }}/ad.keytab'
     remote_src: yes
+  when: client_ad_installation.changed
 
-- include_tasks: 'cleanup.yml'
+- name: Create symbolic link
+  become: True
+  file:
+    force: yes
+    path: '/etc/krb5.keytab'
+    src: '/shared/enrollment/{{ inventory_hostname }}/ad.keytab'
+    state: link
+
+# - include_tasks: 'cleanup.yml'
